var H,Q,u,X,ra;import{r as S,h as W,q as j,o as O,c as l,W as m,a as E,Z as I,m as f,u as G,Y as i,B as w,l as J,f as L,G as M,U as V,d}from"./khao-ui-svelte-dispatchRemoteControlEvent-4.17.8.js";import{W as Y,b as A,o as g}from"./khao-ui-svelte-this-4.17.8.js";import{D as _,w as C}from"./khao-ui-svelte-each-4.17.8.js";import{h as x,N as F}from"./khao-ui-svelte-style-4.17.8.js";H=Object.defineProperty,Q=(a,b,c)=>b in a?H(a,b,{enumerable:!0,configurable:!0,writable:!0,value:c}):a[b]=c,u=(b,a,c)=>Q(b,typeof a!="symbol"?a+"":a,c);class R{constructor(){u(this,"tablet",1024),u(this,"phone",620),u(this,"isTablet",()=>this.isEqualOrSmaller(this.tablet)),u(this,"isPhone",()=>this.isEqualOrSmaller(this.phone)),u(this,"isEqualOrSmaller",a=>window.innerWidth<=a)}}const $=new R;X=S('<li role="tab"><a> </a></li>');const aa={hash:"svelte-yrvm2o",code:`:host {--khao-tab-text-size: var(--khao-sys-size-typography-3);--khao-tab-leading-space: var(--khao-sys-size-regular-2);--khao-tab-trailing-space: var(--khao-sys-size-regular-2);--khao-tab-height: var(--khao-sys-size-regular-6);--khao-tab-width: var(--khao-sys-size-regular-8);--khao-tab-container-shape: var(--khao-sys-shape-corner-small);--khao-tab-active-height: var(--khao-sys-size-regular-7);--khao-tab-text-color: var(--khao-sys-color-neutral30);--khao-tab-state-layer-color: var(--khao-sys-color-neutral50);--khao-tab-border-color: var(--khao-sys-color-secondary);--khao-tab-hover-state-layer-opacity: var(
      --khao-sys-state-hover-state-layer-opacity
    );--khao-tab-focus-state-layer-opacity: var(
      --khao-sys-state-focus-state-layer-opacity
    );--khao-tab-pressed-state-layer-opacity: var(
      --khao-sys-state-pressed-state-layer-opacity
    );}.tab.svelte-yrvm2o {align-items:center;background-color:var(--khao-sys-color-surface-variantd10);border-bottom-width:2px;border-top-left-radius:var(--khao-tab-container-shape);border-top-right-radius:var(--khao-tab-container-shape);border:1px solid var(--khao-tab-border-color);display:inline-flex;flex-direction:row;flex-wrap:nowrap;flex:0 0 auto;font-size:var(--khao-tab-text-size);height:var(--khao-tab-height);justify-content:center;list-style-type:none;padding:0.1rem var(--khao-tab-leading-space) 0.1rem
      var(--khao-tab-trailing-space);text-align:center;width:var(--khao-tab-width);&:hover {text-decoration:none !important;background-color:var(--khao-sys-color-outline);}&:focus-within {text-decoration:none !important;background-color:var(--khao-sys-color-outline);}}.tab-active.svelte-yrvm2o {border-bottom:none;height:var(--khao-tab-active-height);background-color:transparent;}.tab-size-flex.svelte-yrvm2o {--khao-tab-width: 100%;}.tab-size-compact.svelte-yrvm2o {--khao-tab-width: 32px;}.tab-size-medium.svelte-yrvm2o {--khao-tab-width: 64px;}.tab-size-large.svelte-yrvm2o {--khao-tab-width: 96px;}.link.svelte-yrvm2o {font-weight:400;color:var(--khao-tab-text-color);white-space:nowrap;text-decoration:none;min-width:3rem;overflow-x:hidden;text-overflow:ellipsis;margin:0 0.4rem;&:hover {text-decoration:none !important;color:color-mix(
        in srgb,
        var(--khao-tab-text-color),
        var(--khao-tab-layer-color) var(--khao-tab-hover-state-layer-opacity)
      );}&:focus-visible {outline:none;}}.link-active.svelte-yrvm2o {font-weight:700;&:hover {color:inherit;font-weight:700;}}`};function K(p,a){j(a,!0),O(p,aa);let h=l(a,"label",7,""),n=l(a,"href",7,""),o=l(a,"title",7,""),d=l(a,"active",7,"false"),e=l(a,"size",23,()=>$.isPhone()?"compact":"medium"),k=l(a,"key",7,"");var q={get label(){return h()},set label(a=""){h(a),i()},get href(){return n()},set href(a=""){n(a),i()},get title(){return o()},set title(a=""){o(a),i()},get active(){return d()},set active(a="false"){d(a),i()},get size(){return e()},set size(a=$.isPhone()?"compact":"medium"){e(a),i()},get key(){return k()},set key(a=""){k(a),i()}},b=X(),c=m(b),r=m(c,!0);return w(c),w(b),I(()=>{x(b,1,`tab ${d()==="true"?"tab-active":""} tab-size-${e()??""}`,"svelte-yrvm2o"),g(b,"data-key",k()),g(b,"aria-selected",d()==="true"?"true":"false"),g(c,"href",n()),g(c,"title",o()),x(c,1,`link ${d()==="true"?"link-active":""}`,"svelte-yrvm2o"),J(r,h())}),f(p,b),E(q)}customElements.define("khao-tab",W(K,{label:{},href:{},title:{},active:{},size:{},key:{}},[],[],!0));const ta=a=>{if(window.IntersectionObserver){const b=function(b,c){b.forEach(b=>{b.isIntersecting&&(ea(a),c.unobserve(b.target))})};new IntersectionObserver(b,{rootMargin:"0px 0px 0px 0px",threshold:1}).observe(a)}},ea=b=>{const c=b.clientWidth,a=b.querySelector(".tab-bar > li.tab[aria-selected='true']");if(a){const b=a.clientWidth;a.offsetLeft+b>c&&a.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"})}};ra=S('<ul role="tablist"><!></ul>');const oa={hash:"svelte-wrtjtq",code:`:host {--khao-tab-bar-height: var(--khao-sys-size-regular-9);--khao-tab-bar-bg-color: var(--khao-sys-color-background);--khao-tab-bar-scroll-shadow-color: rgba(216, 216, 216, 1);--khao-tab-bar-scroll-shadow-size: 1rem;--khao-tab-bar-scroll-shadow-transparent: rgba(255, 255, 255, 0);}.tab-bar.svelte-wrtjtq {height:var(--khao-tab-bar-height);display:flex;flex-direction:row;flex-wrap:nowrap;justify-content:start;align-items:end;gap:0;margin:0;overflow-x:auto;scrollbar-width:none;padding:0 1px;}.tab-bar.svelte-wrtjtq::-webkit-scrollbar {display:none;}.tab-bar-centered.svelte-wrtjtq {margin-left:auto;margin-right:auto;}.tab-bar-scroll-shadow.svelte-wrtjtq {overflow-x:scroll;background:linear-gradient(
        to right,
        var(--khao-tab-bar-bg-color),
        var(--khao-tab-bar-bg-color),
        var(--khao-tab-bar-scroll-shadow-transparent)
          calc(var(--khao-tab-bar-scroll-shadow-size) * 2)
      ),
      radial-gradient(
        farthest-side at left bottom,
        var(--khao-tab-bar-scroll-shadow-color),
        var(--khao-tab-bar-scroll-shadow-transparent)
      ),
      linear-gradient(
        to left,
        var(--khao-tab-bar-bg-color),
        var(--khao-tab-bar-bg-color),
        var(--khao-tab-bar-scroll-shadow-transparent)
          calc(var(--khao-tab-bar-scroll-shadow-size) * 2)
      ),
      radial-gradient(
        farthest-side at right bottom,
          var(--khao-tab-bar-scroll-shadow-color),
          var(--khao-tab-bar-scroll-shadow-transparent)
        )
        100%;background-color:var(--khao-tab-bar-bg-color);background-repeat:no-repeat;background-attachment:local, scroll, local, scroll;background-size:100% 100%,
      var(--khao-tab-bar-scroll-shadow-size) 100%,
      100% 100%,
      var(--khao-tab-bar-scroll-shadow-size) 100%;height:calc(var(--khao-tab-bar-height)-20px);}`};function sa(o,b){var p,a,q,r;j(b,!0),O(o,oa);let c=l(b,"tabs",7,""),n=l(b,"activeTabKey",7,""),g=l(b,"maxWidth",7,"860px"),h=l(b,"centered",7,"false"),e=l(b,"scrollShadow",7,"false"),k;return G(()=>{ta(k)}),p={get tabs(){return c()},set tabs(a=""){c(a),i()},get activeTabKey(){return n()},set activeTabKey(a=""){n(a),i()},get maxWidth(){return g()},set maxWidth(a="860px"){g(a),i()},get centered(){return h()},set centered(a="false"){h(a),i()},get scrollShadow(){return e()},set scrollShadow(a="false"){e(a),i()}},a=ra(),q=m(a),r=b=>{var a=L(),e=M(a);_(e,17,()=>JSON.parse(c()),C,(c,a)=>{let e=()=>d(a).label,b=()=>d(a).key,f=()=>d(a).href,g=()=>d(a).title,h=()=>d(a).size;{let a=V(()=>n()===b()?"true":"false");K(c,{get key(){return b()},get label(){return e()},get href(){return f()},get title(){return g()},get active(){return d(a)},get size(){return h()}})}}),f(b,a)},Y(q,a=>{c()&&a(r)}),w(a),A(a,a=>k=a,()=>k),I(()=>{x(a,1,`tab-bar ${h()==="true"?"tab-bar-centered":""} ${e()==="true"?"tab-bar-scroll-shadow":""}`,"svelte-wrtjtq"),F(a,`max-width: ${g()??""}`)}),f(o,a),E(p)}customElements.define("khao-tab-bar",W(sa,{tabs:{},activeTabKey:{},maxWidth:{},centered:{},scrollShadow:{}},[],[],!0))