var H,N;import{r as x,h as S,o as E,m as O,q as F,c as h,w as b,u as K,j as c,W,K as j,a as M,Y as m,d as w,B as T,V}from"./khao-ui-svelte-dispatchRemoteControlEvent-4.17.8.js";import{W as y,b as Y}from"./khao-ui-svelte-this-4.17.8.js";import{T as A}from"./khao-ui-button-4.17.8.js";import"./khao-ui-icon-4.17.8.js";import"./khao-ui-svelte-style-4.17.8.js";const D=(b,a)=>{const c=b=>{b.forEach(b=>{b.isIntersecting&&a&&a()})},d={root:document,rootMargin:"0px 0px 100px 0px",threshold:1};new IntersectionObserver(c,d).observe(b)},k=["1"],G=(g,d,f)=>{const c=document.location.href;let e="1",a="2",b=`${c}${d}${a}`;if(c.includes(d)){const f=c.split(d);f.length===2&&(e=f[1].replace("/",""),a=`${parseInt(e,10)+1}`,b=c.replace(`/${e}`,`/${a}`))}k.indexOf(a)===-1?(fetch(b).then(a=>{if(!a.ok)throw new Error(`error loading next page ${b} , perhaps we have reached the end!`);return a.text()}).then(d=>{const a=document.querySelector(`${g}:last-of-type`);var c=document.createElement("template");c.innerHTML=d,c.content.querySelectorAll(g).forEach(c=>{var b;(b=a==null?void 0:a.parentElement)==null||b.appendChild(c)}),f!==void 0&&f(),history.pushState({},"",b)}).catch(a=>{console.log(a)}),k.push(a)):console.log("already added",a)};H=x('<div class="spinner svelte-qlm6m4"></div>');const J={hash:"svelte-qlm6m4",code:`:host {--khao-spinner-color: var(--khao-sys-color-neutral30);--khao-spinner-size: var(--khao-sys-size-regular-10);}.spinner.svelte-qlm6m4 {width:var(--khao-spinner-size);height:var(--khao-spinner-size);border:5px solid var(--khao-spinner-color);border-bottom-color:transparent;border-radius:50%;display:inline-block;box-sizing:border-box;
    animation: svelte-qlm6m4-rotation 1s linear infinite;}

  @keyframes svelte-qlm6m4-rotation {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }`};function L(a){E(a,J);var b=H();O(a,b)}customElements.define("khao-spinner",S(L,{},[],[],!0)),N=x('<div class="infinite-scroll svelte-wtq3d0"><!> <!></div>');const Q={hash:"svelte-wtq3d0",code:".infinite-scroll.svelte-wtq3d0 {display:flex;justify-content:space-around;width:100%;height:2rem;}"};function R(t,a){var u,d,f,r,s,q;F(a,!0),E(t,Q);let g=h(a,"querySelector",7),o=h(a,"paginationSlug",7),i=h(a,"buttonLabel",7),k=h(a,"numberOfPages",7,"1"),l=h(a,"showButtonOnFirstLoad",7,"true"),e=b(!1),n=b(!1),v=b(1);const C=new CustomEvent("khao-infinite-scroll-loaded-more",{bubbles:!0}),B=()=>{w(v)<parseInt(k(),10)&&c(e,!0)},z=()=>{G(g(),o(),x),c(e,!1),c(n,!0),V(v)},x=()=>{c(e,!1),c(n,!1),window.dispatchEvent(C)};let p;return K(()=>{l()==="true"&&c(e,!0),D(p,B)}),u={get querySelector(){return g()},set querySelector(a){g(a),m()},get paginationSlug(){return o()},set paginationSlug(a){o(a),m()},get buttonLabel(){return i()},set buttonLabel(a){i(a),m()},get numberOfPages(){return k()},set numberOfPages(a="1"){k(a),m()},get showButtonOnFirstLoad(){return l()},set showButtonOnFirstLoad(a="true"){l(a),m()}},d=N(),f=W(d),r=a=>{A(a,{get label(){return i()},onClick:z})},y(f,a=>{w(e)&&a(r)}),s=j(f,2),q=a=>{L(a)},y(s,a=>{w(n)&&a(q)}),T(d),Y(d,a=>p=a,()=>p),O(t,d),M(u)}customElements.define("khao-infinite-scroll",S(R,{querySelector:{},paginationSlug:{},buttonLabel:{},numberOfPages:{},showButtonOnFirstLoad:{}},[],[],!0))